### ISSUE TITLE
Provide `hostname` as alternative to `hostnameclt` per default.

### ISSUE THREAD

**Issue by flybyray** [AlmaLinux/wsl-images#23]
https://github.com/microsoft/WSL/issues/2380#issuecomment-1101767320

**Comment by srbala** [comment]
@flybyray are you having issues getting a hostname with Almalinux WSL? Screen capture or log would help to analyze.

**Comment by flybyray** [comment]
Sometimes it might be relevant to set the hostname manually. Via some script. As you can see from the above link this is a typical problem because WSL has no systemd running.

```
$ hostnamectl
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
[robert.rettig@LAPTOP-robert-rettig:~]$ sudo dnf history list
```

To make sure some work arround like the linked one work you need to install `hostname`. I would expect it to be default in an WSL image.

```
$ sudo dnf history list
ID     | Command line                                                                                                          | Date and time    | Action(s)      | Altered
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     2 | install hostname                                                                                                      | 2022-04-18 23:04 | Install        |    1
     1 | install --installroot /mnt/sys-root --releasever 8 --setopt install_weak_deps=false --nodocs -y bash binutils coreuti | 2021-12-14 03:47 | Install        |  199 EE
```

**Comment by srbala** [comment]
@flybyray we can certainly add `hostname` package into the default image. Due to the current architectural design of WSL, `hostnamectl` command will result in an error.

There are few alternatives developed by the community to workaround `systemd` default issue, some discussions on [ask ubuntu](https://askubuntu.com/questions/1379425/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate), you can find more results on research.
